### ISSUE TITLE
Can't download any apk from https://octogram.site/

### ISSUE THREAD

**Issue by FjKantarell51** [OctoGramApp/Website#1]

**Comment by kuogi** [comment]
The issue will be closed as soon as the first stable is published (and consequently published on the site and AppCenter). Currently, a download from ApkPure of the latest alpha is available on the site.

**Comment by Pikachuvitoria** [comment]
@kuogi 😏

**Comment by null-nick** [comment]
fixed 94145901b721d48a99fa47ccd768f0ba4d4ed6d3
